### ISSUE TITLE
server destroy instance after couple hours

### ISSUE THREAD

**Issue by Teals53** [imayushsaini/Bombsquad-Ballistica-Modded-Server#100]
no clue why its happening and since the log systems are broken on modded server script i cant figure out whats happening but i can see the server overloaded on aws monitoring after a couple hour which is not happening on normal server version

api8 branch

**Comment by Teals53** [comment]
for fix it use restart feature and do it every hour 

6h restart in default causing crash on server

**Comment by imayushsaini** [comment]
what do you mean by log system broken? can you please elaborate on the actual issue?
and what system specs are you running the server on ? as mentioned in the readme minimum 1GB of free memory is required (which does not include memory occupied by OS or other apps). Check the monitor correctly to know what resource is going out of capacity, then increase power of your machine.

**Comment by Teals53** [comment]
the log system is working sorry i just didnt realize it due to old trash logs on the main branch

for crash thing its 2vcpu 1gb ram and pretty sure its enough also the fix i did is working but idk why its crashing in long term restart phases

**Comment by imayushsaini** [comment]
As mentioned in above comment and in readme file , minimum reIquirement to run this project is 1GB free memory, your server memory is low and can't afford to handle mods. I don't know why you think its enough when it's clearly documented.

**Comment by Teals53** [comment]
cuz on windows i can run servers with 100mb free ram space since windows took 900mb of 1gb without any issue but on linux with ur server base it creates problems on 6h restart phase on 1h restart it works well

**Comment by imayushsaini** [comment]
this project is for linux only , you are running something else on Windows and comparing two different things.
Your server is not following minimum system requirements so such crashes are expected.
