### ISSUE TITLE
Some errors after join the server

### ISSUE THREAD

**Issue by PixelPBA** [imayushsaini/Bombsquad-Ballistica-Modded-Server#17]
After players join the server an error appears in the terminal. 

![image](https://user-images.githubusercontent.com/96769297/147547542-f72276fb-3283-459a-a2a3-1fdd5f56f98c.png)

**Comment by imayushsaini** [comment]
fixed ; update your scripts.

**Comment by PixelPBA** [comment]
Wait. I use your scripts, not mine or anything else. This is your job and these are your scripts. You may say that you don't want to accompany your job.

**Comment by imayushsaini** [comment]
lol, I meant update scripts on your server  . Since I cant hack in to your server and update them , I updated them here on this repo.
you have to pull changes yourself manually .
You will also see a message in your console like "UPDATES AVAILABLE".

**Comment by PixelPBA** [comment]
My bad! Didn't understand you. Thanks a lot. May I buy a cup of beer to you? :)
