### ISSUE TITLE
Text animation for tags like owners and admins

### ISSUE THREAD

**Issue by JeetModder** [imayushsaini/Bombsquad-Ballistica-Modded-Server#41]
Does it includes text animation for owners and admins?

**Comment by SenjuZoro** [comment]
Could you define "text animations" ?

**Comment by JeetModder** [comment]
Prefix tag animation can't find it, like color of owner text changes randomly like disco.

**Comment by SenjuZoro** [comment]
that doesn't exist. instead you can only set a specific colour for a player / admin in roles.py

**Comment by itsre3** [comment]
I'm sure this is what this guy meant

https://user-images.githubusercontent.com/105688454/175751916-6ac2b574-c3ba-476f-b361-b5cc44e64f50.mp4

**Comment by SenjuZoro** [comment]
> I'm sure this is what this guy meant
> 
>  screen-20220625-014224.mp4

Pull Request when?

**Comment by itsre3** [comment]
> > I'm sure this is what this guy meant
> > screen-20220625-014224.mp4
> 
> Pull Request when?

Lemme see if I can

**Comment by Pcmodder** [comment]
Yes please add those in files.

**Comment by JeetModder** [comment]
> I'm sure this is what this guy meant
> 
>  screen-20220625-014224.mp4

Yes please add this on files.

**Comment by SenjuZoro** [comment]
> 

if you are able to merge it to bcs, GREAT! 
but if not
then send code here, perhaps we can help to implement it to bcs scripts
