### ISSUE TITLE
server goes off and does not stay 24/7 

### ISSUE THREAD

**Issue by FANAIRL** [imayushsaini/Bombsquad-Ballistica-Modded-Server#88]
Hi when ever i host i can't make server stay online if im online...plz help

**Comment by yoyo-2410** [comment]
use this commands frm next
 "sudo apt update
apt list --upgradable
apt list -a
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3-pip python3.10-dev python3.10-venv
git clone https://github.com/imayushsaini/Bombsquad-Ballistica-Modded-Server

cd Bombsquad-Ballistica-Modded-Server
chmod 777 bombsquad_server
chmod 777 dist/bombsquad_headless
tmux
./bombsquad_server"

to turn off a server use "pkill tmux"

**Comment by FANAIRL** [comment]
Thank you very much it really worked and i apologise for the trouble and time you took to assist me. i am truely honored

________________________________

**Comment by yoyo-2410** [comment]
Np you're welcome
