### ISSUE TITLE
Add pb-id on .json not work

### ISSUE THREAD

**Issue by CarlosMmagno** [imayushsaini/Bombsquad-Ballistica-Modded-Server#89]
When i add my PB on owner's PB id's..The archive rewrite for The original when i start The server.. what is happening ?

**Comment by RAZA6377** [comment]
> When i add my PB on owner's PB id's..The archive rewrite for The original when i start The server.. what is happening ?

First turn off server using exit() then download roles.json and open it in an editor and enter your pb there then re-upload file in script and delete roles.json.backup then turn on server but if still u get this problem then u r making an issue in file so it's keep changing to default.
Thank You

**Comment by imayushsaini** [comment]
yeah  as Raza mentioned make sure your are not editing a running server , else server will over write it.
also if make any error in editing a file , like any syntax error (missing or command or invalid bracket) server will roll back that change with .backup file.
