### ISSUE TITLE
on api8 version the server doesnt use our config settings

### ISSUE THREAD

**Issue by Teals53** [imayushsaini/Bombsquad-Ballistica-Modded-Server#97]
for example using FFA as a server name and 5 player instead of our own settings and all others doesnt work

**Comment by Teals53** [comment]
bcs its .yaml it must be .toml on api8 anyone facing this issue just use ur toml instead of this repo yaml

**Comment by vishal332008** [comment]
Hi bro, here you go, rename your file from config.yaml to config.toml and use this.
https://github.com/imayushsaini/Bombsquad-Ballistica-Modded-Server/blob/c73d92665c3406769b19ac1f759ba978f2a2dfba/config.toml

**Comment by imayushsaini** [comment]
updated config to .toml
